In [29]:
import pandas as pd
from imputation_strategies import impute_numerical_mean, impute_numerical_median, impute_numerical_knn, impute_numerical_multiple, impute_numerical_decision_tree, impute_categorical_mode, impute_categorical_new_category, impute_categorical_decision_tree

ImportError: cannot import name 'impute_numerical_decision_tree' from 'imputation_strategies' (/Users/leon/Documents/Impact-of-data-quality-on-machine-learning-models/Code/Data quality dimension/Completeness/imputation_strategies.py)

In [40]:
df = pd.read_csv('../../../Data/Classification/Indicators of Heart Disease/Completeness/NaN/heart_2022_10%.csv')
df

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,NaN,9.0,None of them,False,...,1.60,71.67,27.99,False,False,True,True,"Yes, received Tdap",False,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,True,NaN,None of them,NaN,...,1.78,NaN,30.13,False,False,True,True,"Yes, received tetanus shot but not sure what type",False,No
2,NaN,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,False,8.0,"6 or more, but not all",False,...,NaN,108.86,NaN,True,False,False,True,NaN,False,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,True,9.0,None of them,False,...,1.70,NaN,31.32,NaN,NaN,NaN,True,"No, did not receive any tetanus shot in the pa...",False,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,True,5.0,1 to 5,False,...,1.55,79.38,33.07,False,False,True,NaN,"No, did not receive any tetanus shot in the pa...",False,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246017,Virgin Islands,Male,Very good,0.0,0.0,Within past 2 years (1 year but less than 2 ye...,True,6.0,None of them,False,...,1.78,102.06,32.28,True,False,False,False,"Yes, received tetanus shot but not sure what type",False,No
246018,Virgin Islands,Female,Fair,0.0,7.0,Within past year (anytime less than 12 months ...,True,7.0,NaN,False,...,1.93,90.72,24.34,False,False,False,False,"No, did not receive any tetanus shot in the pa...",False,Yes
246019,Virgin Islands,Male,Good,0.0,15.0,Within past year (anytime less than 12 months ...,True,7.0,1 to 5,False,...,1.68,83.91,29.86,True,True,True,True,"Yes, received tetanus shot but not sure what type",False,Yes
246020,Virgin Islands,Female,Excellent,2.0,2.0,Within past year (anytime less than 12 months ...,True,7.0,None of them,False,...,1.70,NaN,28.66,False,True,True,False,"Yes, received tetanus shot but not sure what type",False,No
246021,Virgin Islands,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,False,5.0,None of them,True,...,1.83,108.86,32.55,False,True,True,True,"No, did not receive any tetanus shot in the pa...",False,NaN

In [35]:
df_mean = impute_numerical_mean(df.copy())
df_mean

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,NaN,9.000000,None of them,False,...,1.600000,71.670000,27.990000,False,False,True,True,"Yes, received Tdap",False,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,True,7.021999,None of them,NaN,...,1.780000,83.624478,30.130000,False,False,True,True,"Yes, received tetanus shot but not sure what type",False,No
2,NaN,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,False,8.000000,"6 or more, but not all",False,...,1.705137,108.860000,28.660448,True,False,False,True,NaN,False,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,True,9.000000,None of them,False,...,1.700000,83.624478,31.320000,NaN,NaN,NaN,True,"No, did not receive any tetanus shot in the pa...",False,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,True,5.000000,1 to 5,False,...,1.550000,79.380000,33.070000,False,False,True,NaN,"No, did not receive any tetanus shot in the pa...",False,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246017,Virgin Islands,Male,Very good,0.0,0.0,Within past 2 years (1 year but less than 2 ye...,True,6.000000,None of them,False,...,1.780000,102.060000,32.280000,True,False,False,False,"Yes, received tetanus shot but not sure what type",False,No
246018,Virgin Islands,Female,Fair,0.0,7.0,Within past year (anytime less than 12 months ...,True,7.000000,NaN,False,...,1.930000,90.720000,24.340000,False,False,False,False,"No, did not receive any tetanus shot in the pa...",False,Yes
246019,Virgin Islands,Male,Good,0.0,15.0,Within past year (anytime less than 12 months ...,True,7.000000,1 to 5,False,...,1.680000,83.910000,29.860000,True,True,True,True,"Yes, received tetanus shot but not sure what type",False,Yes
246020,Virgin Islands,Female,Excellent,2.0,2.0,Within past year (anytime less than 12 months ...,True,7.000000,None of them,False,...,1.700000,83.624478,28.660000,False,True,True,False,"Yes, received tetanus shot but not sure what type",False,No
246021,Virgin Islands,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,False,5.000000,None of them,True,...,1.830000,108.860000,32.550000,False,True,True,True,"No, did not receive any tetanus shot in the pa...",False,NaN

In [36]:
df_median = impute_numerical_median(df.copy())
df_median

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,NaN,9.0,None of them,False,...,1.60,71.67,27.99,False,False,True,True,"Yes, received Tdap",False,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,True,7.0,None of them,NaN,...,1.78,81.65,30.13,False,False,True,True,"Yes, received tetanus shot but not sure what type",False,No
2,NaN,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,False,8.0,"6 or more, but not all",False,...,1.70,108.86,27.46,True,False,False,True,NaN,False,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,True,9.0,None of them,False,...,1.70,81.65,31.32,NaN,NaN,NaN,True,"No, did not receive any tetanus shot in the pa...",False,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,True,5.0,1 to 5,False,...,1.55,79.38,33.07,False,False,True,NaN,"No, did not receive any tetanus shot in the pa...",False,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246017,Virgin Islands,Male,Very good,0.0,0.0,Within past 2 years (1 year but less than 2 ye...,True,6.0,None of them,False,...,1.78,102.06,32.28,True,False,False,False,"Yes, received tetanus shot but not sure what type",False,No
246018,Virgin Islands,Female,Fair,0.0,7.0,Within past year (anytime less than 12 months ...,True,7.0,NaN,False,...,1.93,90.72,24.34,False,False,False,False,"No, did not receive any tetanus shot in the pa...",False,Yes
246019,Virgin Islands,Male,Good,0.0,15.0,Within past year (anytime less than 12 months ...,True,7.0,1 to 5,False,...,1.68,83.91,29.86,True,True,True,True,"Yes, received tetanus shot but not sure what type",False,Yes
246020,Virgin Islands,Female,Excellent,2.0,2.0,Within past year (anytime less than 12 months ...,True,7.0,None of them,False,...,1.70,81.65,28.66,False,True,True,False,"Yes, received tetanus shot but not sure what type",False,No
246021,Virgin Islands,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,False,5.0,None of them,True,...,1.83,108.86,32.55,False,True,True,True,"No, did not receive any tetanus shot in the pa...",False,NaN

In [38]:
df_knn = impute_numerical_knn(df.copy())
df_knn

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,NaN,9.0,None of them,False,...,1.600,71.670,27.990,False,False,True,True,"Yes, received Tdap",False,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,True,6.6,None of them,NaN,...,1.780,86.182,30.130,False,False,True,True,"Yes, received tetanus shot but not sure what type",False,No
2,NaN,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,False,8.0,"6 or more, but not all",False,...,1.558,108.860,33.698,True,False,False,True,NaN,False,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,True,9.0,None of them,False,...,1.700,91.716,31.320,NaN,NaN,NaN,True,"No, did not receive any tetanus shot in the pa...",False,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,True,5.0,1 to 5,False,...,1.550,79.380,33.070,False,False,True,NaN,"No, did not receive any tetanus shot in the pa...",False,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246017,Virgin Islands,Male,Very good,0.0,0.0,Within past 2 years (1 year but less than 2 ye...,True,6.0,None of them,False,...,1.780,102.060,32.280,True,False,False,False,"Yes, received tetanus shot but not sure what type",False,No
246018,Virgin Islands,Female,Fair,0.0,7.0,Within past year (anytime less than 12 months ...,True,7.0,NaN,False,...,1.930,90.720,24.340,False,False,False,False,"No, did not receive any tetanus shot in the pa...",False,Yes
246019,Virgin Islands,Male,Good,0.0,15.0,Within past year (anytime less than 12 months ...,True,7.0,1 to 5,False,...,1.680,83.910,29.860,True,True,True,True,"Yes, received tetanus shot but not sure what type",False,Yes
246020,Virgin Islands,Female,Excellent,2.0,2.0,Within past year (anytime less than 12 months ...,True,7.0,None of them,False,...,1.700,81.282,28.660,False,True,True,False,"Yes, received tetanus shot but not sure what type",False,No
246021,Virgin Islands,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,False,5.0,None of them,True,...,1.830,108.860,32.550,False,True,True,True,"No, did not receive any tetanus shot in the pa...",False,NaN

In [39]:
df_multiple = impute_numerical_multiple(df.copy())
df_multiple

/opt/anaconda3/envs/Impact-of-data-quality-on-machine-learning-models/lib/python3.11/site-packages/sklearn/impute/_iterative.py:825: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,NaN,9.000000,None of them,False,...,1.600000,71.670000,27.99000,False,False,True,True,"Yes, received Tdap",False,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,True,7.096086,None of them,NaN,...,1.780000,95.290173,30.13000,False,False,True,True,"Yes, received tetanus shot but not sure what type",False,No
2,NaN,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,False,8.000000,"6 or more, but not all",False,...,1.828486,108.860000,33.10887,True,False,False,True,NaN,False,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,True,9.000000,None of them,False,...,1.700000,90.676348,31.32000,NaN,NaN,NaN,True,"No, did not receive any tetanus shot in the pa...",False,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,True,5.000000,1 to 5,False,...,1.550000,79.380000,33.07000,False,False,True,NaN,"No, did not receive any tetanus shot in the pa...",False,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246017,Virgin Islands,Male,Very good,0.0,0.0,Within past 2 years (1 year but less than 2 ye...,True,6.000000,None of them,False,...,1.780000,102.060000,32.28000,True,False,False,False,"Yes, received tetanus shot but not sure what type",False,No
246018,Virgin Islands,Female,Fair,0.0,7.0,Within past year (anytime less than 12 months ...,True,7.000000,NaN,False,...,1.930000,90.720000,24.34000,False,False,False,False,"No, did not receive any tetanus shot in the pa...",False,Yes
246019,Virgin Islands,Male,Good,0.0,15.0,Within past year (anytime less than 12 months ...,True,7.000000,1 to 5,False,...,1.680000,83.910000,29.86000,True,True,True,True,"Yes, received tetanus shot but not sure what type",False,Yes
246020,Virgin Islands,Female,Excellent,2.0,2.0,Within past year (anytime less than 12 months ...,True,7.000000,None of them,False,...,1.700000,83.087853,28.66000,False,True,True,False,"Yes, received tetanus shot but not sure what type",False,No
246021,Virgin Islands,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,False,5.000000,None of them,True,...,1.830000,108.860000,32.55000,False,True,True,True,"No, did not receive any tetanus shot in the pa...",False,NaN

In [7]:
df_random_forest = impute_numerical_decision_tree(df.copy())
df_random_forest

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,NaN,9.0,None of them,False,...,1.60,71.67,27.99,False,False,True,True,"Yes, received Tdap",False,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,True,6.0,None of them,NaN,...,1.78,95.25,30.13,False,False,True,True,"Yes, received tetanus shot but not sure what type",False,No
2,NaN,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,False,8.0,"6 or more, but not all",False,...,1.75,108.86,35.44,True,False,False,True,NaN,False,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,True,9.0,None of them,False,...,1.70,90.72,31.32,NaN,NaN,NaN,True,"No, did not receive any tetanus shot in the pa...",False,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,True,5.0,1 to 5,False,...,1.55,79.38,33.07,False,False,True,NaN,"No, did not receive any tetanus shot in the pa...",False,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246017,Virgin Islands,Male,Very good,0.0,0.0,Within past 2 years (1 year but less than 2 ye...,True,6.0,None of them,False,...,1.78,102.06,32.28,True,False,False,False,"Yes, received tetanus shot but not sure what type",False,No
246018,Virgin Islands,Female,Fair,0.0,7.0,Within past year (anytime less than 12 months ...,True,7.0,NaN,False,...,1.93,90.72,24.34,False,False,False,False,"No, did not receive any tetanus shot in the pa...",False,Yes
246019,Virgin Islands,Male,Good,0.0,15.0,Within past year (anytime less than 12 months ...,True,7.0,1 to 5,False,...,1.68,83.91,29.86,True,True,True,True,"Yes, received tetanus shot but not sure what type",False,Yes
246020,Virgin Islands,Female,Excellent,2.0,2.0,Within past year (anytime less than 12 months ...,True,7.0,None of them,False,...,1.70,83.01,28.66,False,True,True,False,"Yes, received tetanus shot but not sure what type",False,No
246021,Virgin Islands,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,False,5.0,None of them,True,...,1.83,108.86,32.55,False,True,True,True,"No, did not receive any tetanus shot in the pa...",False,NaN

In [40]:
df_mode = impute_categorical_mode(df.copy())
df_mode

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,True,9.0,None of them,False,...,1.60,71.67,27.99,False,False,True,True,"Yes, received Tdap",False,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,True,NaN,None of them,False,...,1.78,NaN,30.13,False,False,True,True,"Yes, received tetanus shot but not sure what type",False,No
2,Washington,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,False,8.0,"6 or more, but not all",False,...,NaN,108.86,NaN,True,False,False,True,"No, did not receive any tetanus shot in the pa...",False,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,True,9.0,None of them,False,...,1.70,NaN,31.32,True,False,True,True,"No, did not receive any tetanus shot in the pa...",False,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,True,5.0,1 to 5,False,...,1.55,79.38,33.07,False,False,True,False,"No, did not receive any tetanus shot in the pa...",False,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246017,Virgin Islands,Male,Very good,0.0,0.0,Within past 2 years (1 year but less than 2 ye...,True,6.0,None of them,False,...,1.78,102.06,32.28,True,False,False,False,"Yes, received tetanus shot but not sure what type",False,No
246018,Virgin Islands,Female,Fair,0.0,7.0,Within past year (anytime less than 12 months ...,True,7.0,None of them,False,...,1.93,90.72,24.34,False,False,False,False,"No, did not receive any tetanus shot in the pa...",False,Yes
246019,Virgin Islands,Male,Good,0.0,15.0,Within past year (anytime less than 12 months ...,True,7.0,1 to 5,False,...,1.68,83.91,29.86,True,True,True,True,"Yes, received tetanus shot but not sure what type",False,Yes
246020,Virgin Islands,Female,Excellent,2.0,2.0,Within past year (anytime less than 12 months ...,True,7.0,None of them,False,...,1.70,NaN,28.66,False,True,True,False,"Yes, received tetanus shot but not sure what type",False,No
246021,Virgin Islands,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,False,5.0,None of them,True,...,1.83,108.86,32.55,False,True,True,True,"No, did not receive any tetanus shot in the pa...",False,No

In [41]:
df_new_category = impute_categorical_new_category(df.copy())
df_new_category

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,Missing,9.0,None of them,False,...,1.6,71.67,27.99,False,False,True,True,"Yes, received Tdap",False,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,True,Missing,None of them,Missing,...,1.78,Missing,30.13,False,False,True,True,"Yes, received tetanus shot but not sure what type",False,No
2,Missing,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,False,8.0,"6 or more, but not all",False,...,Missing,108.86,Missing,True,False,False,True,Missing,False,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,True,9.0,None of them,False,...,1.7,Missing,31.32,Missing,Missing,Missing,True,"No, did not receive any tetanus shot in the pa...",False,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,True,5.0,1 to 5,False,...,1.55,79.38,33.07,False,False,True,Missing,"No, did not receive any tetanus shot in the pa...",False,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246017,Virgin Islands,Male,Very good,0.0,0.0,Within past 2 years (1 year but less than 2 ye...,True,6.0,None of them,False,...,1.78,102.06,32.28,True,False,False,False,"Yes, received tetanus shot but not sure what type",False,No
246018,Virgin Islands,Female,Fair,0.0,7.0,Within past year (anytime less than 12 months ...,True,7.0,Missing,False,...,1.93,90.72,24.34,False,False,False,False,"No, did not receive any tetanus shot in the pa...",False,Yes
246019,Virgin Islands,Male,Good,0.0,15.0,Within past year (anytime less than 12 months ...,True,7.0,1 to 5,False,...,1.68,83.91,29.86,True,True,True,True,"Yes, received tetanus shot but not sure what type",False,Yes
246020,Virgin Islands,Female,Excellent,2.0,2.0,Within past year (anytime less than 12 months ...,True,7.0,None of them,False,...,1.7,Missing,28.66,False,True,True,False,"Yes, received tetanus shot but not sure what type",False,No
246021,Virgin Islands,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,False,5.0,None of them,True,...,1.83,108.86,32.55,False,True,True,True,"No, did not receive any tetanus shot in the pa...",False,Missing

In [30]:
df_categorical_decision_tree = impute_categorical_decision_tree(df.copy())
df_categorical_decision_tree

NameError: name 'impute_categorical_decision_tree' is not defined

In [ ]:
# df_hot_deck = impute_by_hot_deck(df.copy())
# df_hot_deck

ValueError: 2